[SyncWithGitLab] Sync from GitLab commit 04ff4a18

diff --git a/jobs/docker.yml b/jobs/docker.yml
--- a/jobs/docker.yml
+++ b/jobs/docker.yml
@@ -7,7 +7,18 @@
 
 .docker_validate_build:
   script:
-    - docker build --check .
+    - |
+      if [ -f docker-compose.yml ]; then
+        docker compose config && echo "OK" || (echo "ERROR" && exit 1)
+      else
+        echo "No docker-compose.yml found, skipping"
+      fi
+  tags:
+    - shell
+
+.docker_validate_compose_file:
+  script:
+    - docker compose config && echo "OK" || (echo "ERROR" && exit 1)
   tags:
     - shell
 
